name: build-artifacts

on:
  push:
    paths:
      - "src/**"
      - "layer_packages/**"
    branches-ignore:
      - main

env:
  SRC_DIR: "src"
  LAYER_DIR: "layer_packages"
  PY_PKG_DIR: "packages"
  LAYERS: (xray)
  PY_VER: "3.8.12"
  FUNCTION: "movies"

jobs:
  create-function-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        id: checkout
        uses: actions/checkout@v3
      - name: Setup python caching
        id: cache
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.12"
          cache: "pip"
      - name: install  packages
        id: install-packages
        run: |
          cd "$SRC_DIR"
          mkdir -p "$PY_PKG_DIR"
          pip3 install -r requirements.txt --target "$PY_PKG_DIR" -q
      - name: create artifact zip
        id: create-function-artifact
        run: |
          cd "$SRC_DIR/$PY_PKG_DIR"
          zip -rq ../"$FUNCTION.zip" .

          cd ..
          zip -g "$FUNCTION.zip" "$FUNCTION.py"
          ls
      - name: upload function artifact
        uses: actions/upload-artifact@v3
        with:
          name: upload-function-artifact
          path: |
            ${{ env.SRC_DIR }}/${{ env.FUNCTION }}.zip

  create-layer-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        id: checkout
        uses: actions/checkout@v3
      - name: Setup python caching
        id: cache
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.12"
          cache: "pip"
      - name: install  packages
        id: install-packages
        run: |
          cd "$LAYER_DIR"
          for LAYER in "$LAYERS"; do
            mkdir -p "$LAYER-$PY_PKG_DIR"
            pip3 install -r requirements.txt --no-deps --target "$LAYER-$PY_PKG_DIR" -q

            cd "$LAYER-$PY_PKG_DIR"
            zip -rq ../$LAYER_packages.zip .
          done
          ls
      - name: upload layer artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload-layer-artifacts
          path: |
            ${{ env.LAYER_DIR }}/*.zip
