name: continuous-deployment

on:
  push:
    branches:
      - main

env:
  TFM_DIR: "terraform"
  CFG_DIR: "configuration"
  FUNCTION: "mvdb"
  LAYERS: "xray"

jobs:
  # CALL WORKFLOW tag-release
  tag-release:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tag-release.yml@main

    # CALL WORKFLOW build artifacts
  build-artifacts:
    uses: indigo-tangerine/shared-workflows/.github/workflows/build-lambda-artifacts.yml@main
    with:
      lambda-function-name: mvdb
      lambda-layers: "xray"

  # CALL WORKFLOW tfm-plan-apply
  tfm-plan-apply:
    needs: [tag-release, build-artifacts]
    uses: indigo-tangerine/shared-workflows/.github/workflows/tfm-plan-apply-lambda.yml@main
    with:
      configuration-dir: configuration
      terraform-dir: terraform
      aws-region: "eu-west-1"
      download-artifacts: true
    secrets:
      aws-access-key-id: ${{ secrets.CICD_AUTOMATION_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.CICD_AUTOMATION_AWS_SECRET_ACCESS_KEY }}
      aws-cicd-automation-role-external-id: ${{ secrets.ITC_AWS_IAM_EXTERNAL_ID }}
      aws-cicd-automation-github-role: ${{ secrets.CICD_AUTOMATION_GITHUB_ACTIONS_ROLE }}

  # CALL WORKFLOW changelog
  update-changelog:
    needs: [tfm-plan-apply]
    uses: indigo-tangerine/shared-workflows/.github/workflows/update-changelog.yml@main
    secrets:
      access_token: ${{ secrets.CICD_AUTOMATION_PAT }}
